name: Build & Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependancies
        run: npm ci

      - name: Build
        run: npm start

      - name: Trial 01
        run: |
          echo ${{ github.actor }}

      - name: Setup Github Account
        run: |
          git config user.email "nka.debug@gmail.com"
          git config user.name "nkadebug"

      - name: Select GH-Pages Branch
        run: |
          {
            git checkout "gh-pages"
            echo "Swtched to GH Pages Branch"
          } || {
            git checkout -b "gh-pages" 
            echo "Created and Swtched to GH Pages Branch"
            git rm -rf . 
            git checkout master -- .gitignore
          }

      - name: Push To GH-Pages
        run: |
          cp -r dist/* .
          git add .
          set +e
          if git status | grep 'new file\|modified'
          then
              set -e
              git commit -m "Auto Updated $(date)"
              git push origin gh-pages
          else
              set -e
              echo "No changes since last run"
          fi
          echo "finish"
