name: Build & Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependancies
        run: npm ci

      - name: Build
        run: npm start

      - name: Setup Github Account
        run: git config user.name ${{ github.actor }}
      - run: git branch -a
      - name: Select GH-Pages Branch
        run: |
          # git pull
          set +e
          if git branch -a | grep 'remotes/origin/gh-pages'
          then
            set -e
            git checkout "gh-pages"
            echo 'Exists'
          else
            set-e
            git checkout -b "gh-pages" 
            git rm -rf . 
            git checkout master -- .gitignore
            echo 'Created'
          fi

      - name: Push To GH-Pages
        run: |
          cp -r dist/* .
          git add .
          set +e
          if git status | grep 'new file\|modified'
          then
              set -e
              git commit -m "Auto Updated $(date)"
              git push origin gh-pages
          else
              set -e
              echo "No changes since last run"
          fi
          echo "finish"
